"""Gateway-signed auth contracts for Adaptix domain services.

Domain services behind the Adaptix API gateway trust identity headers
injected after JWT validation only when those headers are accompanied by
a gateway HMAC proof. This module provides the canonical AuthContext model
and the get_auth_context FastAPI dependency used by downstream domain
services.

Trusted headers injected by the gateway:
  X-User-ID     — UUID of the authenticated user (JWT ``sub`` claim)
  X-Tenant-ID   — UUID of the authenticated tenant (JWT ``tid`` claim)
  X-User-Email  — Email of the authenticated user (JWT ``email`` claim)
    X-Adaptix-Gateway-Timestamp  — Unix timestamp generated by the gateway
    X-Adaptix-Gateway-Signature  — HMAC-SHA256 over timestamp/user/tenant/email
"""
from __future__ import annotations

import hmac
import hashlib
import os
import time
from typing import Annotated
from uuid import UUID

from fastapi import Depends, Header, HTTPException, status
from pydantic import BaseModel


GATEWAY_SHARED_SECRET_ENV = "ADAPTIX_GATEWAY_SHARED_SECRET"
GATEWAY_SIGNATURE_MAX_AGE_SECONDS = 300


class AuthContext(BaseModel):
    """Resolved gateway-injected authentication context.

    Attributes:
        user_id: UUID of the authenticated user.
        tenant_id: UUID of the authenticated tenant.
        email: Email address of the authenticated user.
    """

    user_id: UUID
    tenant_id: UUID
    email: str

    model_config = {"frozen": True}


async def get_auth_context(
    x_user_id: Annotated[str | None, Header(alias="X-User-ID")] = None,
    x_tenant_id: Annotated[str | None, Header(alias="X-Tenant-ID")] = None,
    x_user_email: Annotated[str | None, Header(alias="X-User-Email")] = None,
    x_gateway_timestamp: Annotated[
        str | None,
        Header(alias="X-Adaptix-Gateway-Timestamp"),
    ] = None,
    x_gateway_signature: Annotated[
        str | None,
        Header(alias="X-Adaptix-Gateway-Signature"),
    ] = None,
) -> AuthContext:
    """FastAPI dependency: extract authenticated identity from signed gateway headers.

    The Adaptix gateway validates the caller's JWT and injects ``X-User-ID``,
    ``X-Tenant-ID``, and ``X-User-Email`` into every forwarded request. This
    dependency accepts those headers only when the gateway also provides a
    fresh HMAC signature. Requests without complete identity headers, invalid
    UUID values, missing gateway signature material, stale timestamps, or a
    signature mismatch are rejected.

    Args:
        x_user_id: User UUID from the ``X-User-ID`` header.
        x_tenant_id: Tenant UUID from the ``X-Tenant-ID`` header.
        x_user_email: User email from the ``X-User-Email`` header.
        x_gateway_timestamp: Gateway signature timestamp.
        x_gateway_signature: Gateway HMAC-SHA256 proof.

    Returns:
        AuthContext with resolved user and tenant identity.

    Raises:
        HTTPException: 401 if any required identity/signature header is absent or invalid.
        HTTPException: 503 if gateway signing is not configured for the service.
    """
    # Check identity headers first: missing credentials is always 401, not 503.
    # A request with no credentials is an auth failure, regardless of service config.
    if not x_user_id or not x_tenant_id or not x_user_email:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Missing gateway identity headers (X-User-ID, X-Tenant-ID, X-User-Email).",
        )

    # Only after verifying credentials are present, check that signing is configured.
    # If credentials are present but gateway cannot verify them → 503 (service config issue).
    gateway_secret = os.getenv(GATEWAY_SHARED_SECRET_ENV)
    if not gateway_secret:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail={
                "status": "unavailable",
                "reason": "configuration_missing",
                "required_configuration": [GATEWAY_SHARED_SECRET_ENV],
            },
        )

    if not x_gateway_timestamp or not x_gateway_signature:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail=(
                "Missing gateway signature headers "
                "(X-Adaptix-Gateway-Timestamp, X-Adaptix-Gateway-Signature)."
            ),
        )

    try:
        gateway_timestamp = int(x_gateway_timestamp.strip())
    except (ValueError, AttributeError) as exc:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="X-Adaptix-Gateway-Timestamp header is not a valid Unix timestamp.",
        ) from exc

    if abs(int(time.time()) - gateway_timestamp) > GATEWAY_SIGNATURE_MAX_AGE_SECONDS:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Gateway identity signature has expired.",
        )

    try:
        user_uuid = UUID(x_user_id.strip())
    except (ValueError, AttributeError) as exc:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="X-User-ID header is not a valid UUID.",
        ) from exc

    try:
        tenant_uuid = UUID(x_tenant_id.strip())
    except (ValueError, AttributeError) as exc:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="X-Tenant-ID header is not a valid UUID.",
        ) from exc

    email = x_user_email.strip()
    signature_payload = f"{gateway_timestamp}.{user_uuid}.{tenant_uuid}.{email}".encode("utf-8")
    expected_signature = hmac.new(
        gateway_secret.encode("utf-8"),
        signature_payload,
        hashlib.sha256,
    ).hexdigest()
    if not hmac.compare_digest(expected_signature, x_gateway_signature.strip()):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Gateway identity signature is invalid.",
        )

    return AuthContext(
        user_id=user_uuid,
        tenant_id=tenant_uuid,
        email=email,
    )


__all__ = [
    "AuthContext",
    "GATEWAY_SHARED_SECRET_ENV",
    "GATEWAY_SIGNATURE_MAX_AGE_SECONDS",
    "get_auth_context",
]
