"""Gateway-signed auth contracts for Adaptix domain services.

Domain services behind the Adaptix API gateway trust identity headers
injected after JWT validation only when those headers are accompanied by
a gateway proof. Two verification modes are supported:

RS256 JWT mode (enterprise — primary):
  X-Adaptix-Gateway-Context  — short-lived RS256 JWT signed by the gateway
  using the ADAPTIX_GATEWAY_PUBLIC_KEY (or ADAPTIX_JWT_PUBLIC_KEY) RSA key.
  Claims: sub (user_id), tid (tenant_id), email, roles, exp, iss.
  Issuers accepted: "adaptix-gateway", "adaptix-core".
  When this header is present it takes priority over HMAC.

HMAC mode (backward compat):
  X-User-ID     — UUID of the authenticated user (JWT ``sub`` claim)
  X-Tenant-ID   — UUID of the authenticated tenant (JWT ``tid`` claim)
  X-User-Email  — Email of the authenticated user (JWT ``email`` claim)
  X-Adaptix-Gateway-Timestamp  — Unix timestamp generated by the gateway
  X-Adaptix-Gateway-Signature  — HMAC-SHA256 over timestamp/user/tenant/email
  Still accepted when ADAPTIX_GATEWAY_SHARED_SECRET is configured and
  X-Adaptix-Gateway-Context is absent.
"""

from __future__ import annotations

import hashlib
import hmac
import logging
import os
import time
from typing import Annotated
from uuid import UUID

from fastapi import Header, HTTPException, status
from pydantic import BaseModel

logger = logging.getLogger(__name__)

GATEWAY_SHARED_SECRET_ENV = "ADAPTIX_GATEWAY_SHARED_SECRET"
GATEWAY_PUBLIC_KEY_ENV = "ADAPTIX_GATEWAY_PUBLIC_KEY"
GATEWAY_SIGNATURE_MAX_AGE_SECONDS = 300
GATEWAY_JWT_CONTEXT_HEADER = "X-Adaptix-Gateway-Context"
_TRUSTED_ISSUERS = frozenset({"adaptix-gateway", "adaptix-core"})


class AuthContext(BaseModel):
    """Resolved gateway-injected authentication context.

    Attributes:
        user_id: UUID of the authenticated user.
        tenant_id: UUID of the authenticated tenant.
        email: Email address of the authenticated user.
        roles: List of role strings extracted from the gateway proof.
            Available when the gateway sends an RS256 context JWT that
            includes a ``roles`` claim. Empty list when the HMAC path is used
            (HMAC headers carry no role information).
    """

    user_id: UUID
    tenant_id: UUID
    email: str
    roles: list[str] = []

    model_config = {"frozen": True}


def _verify_rs256_gateway_context(token: str) -> AuthContext:
    """Verify a short-lived RS256 gateway context JWT and return AuthContext.

    Raises:
        HTTPException 503: Public key not configured.
        HTTPException 401: Token invalid, expired, or issuer not trusted.
    """
    public_key_pem = (
        os.getenv(GATEWAY_PUBLIC_KEY_ENV, "").strip()
        or os.getenv("ADAPTIX_JWT_PUBLIC_KEY", "").strip()
    )
    if not public_key_pem:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail={
                "status": "unavailable",
                "reason": "configuration_missing",
                "required_configuration": [GATEWAY_PUBLIC_KEY_ENV],
            },
        )

    try:
        import jwt as pyjwt

        claims = pyjwt.decode(
            token,
            public_key_pem,
            algorithms=["RS256"],
            options={"verify_aud": False},
        )
    except Exception as exc:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Gateway context JWT is invalid or expired.",
        ) from exc

    iss = claims.get("iss", "")
    if iss not in _TRUSTED_ISSUERS:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail=f"Gateway context JWT issuer is not trusted: {iss!r}",
        )

    user_id_raw = claims.get("sub")
    tenant_id_raw = claims.get("tid")
    email = str(claims.get("email") or "").strip()

    if not user_id_raw or not tenant_id_raw:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Gateway context JWT is missing required claims (sub, tid).",
        )

    try:
        user_id = UUID(str(user_id_raw))
        tenant_id = UUID(str(tenant_id_raw))
    except (ValueError, AttributeError) as exc:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Gateway context JWT contains invalid UUID claims.",
        ) from exc

    raw_roles = claims.get("roles", [])
    if isinstance(raw_roles, list):
        roles = [str(r).strip() for r in raw_roles if str(r).strip()]
    elif isinstance(raw_roles, str) and raw_roles.strip():
        roles = [p.strip() for p in raw_roles.split(",") if p.strip()]
    else:
        roles = []

    return AuthContext(
        user_id=user_id,
        tenant_id=tenant_id,
        email=email,
        roles=roles,
    )


async def get_auth_context(
    x_user_id: Annotated[str | None, Header(alias="X-User-ID")] = None,
    x_tenant_id: Annotated[str | None, Header(alias="X-Tenant-ID")] = None,
    x_user_email: Annotated[str | None, Header(alias="X-User-Email")] = None,
    x_gateway_timestamp: Annotated[
        str | None,
        Header(alias="X-Adaptix-Gateway-Timestamp"),
    ] = None,
    x_gateway_signature: Annotated[
        str | None,
        Header(alias="X-Adaptix-Gateway-Signature"),
    ] = None,
    x_gateway_context: Annotated[
        str | None,
        Header(alias="X-Adaptix-Gateway-Context"),
    ] = None,
) -> AuthContext:
    """FastAPI dependency: extract authenticated identity from gateway proof.

    Supports two verification modes, tried in priority order:

    1. RS256 JWT (enterprise): ``X-Adaptix-Gateway-Context`` JWT signed by
       the gateway with the ``ADAPTIX_GATEWAY_PUBLIC_KEY`` RSA private key.
       Returns an ``AuthContext`` that includes ``roles`` from the JWT claims.

    2. HMAC (backward compat): ``X-Adaptix-Gateway-Signature`` HMAC-SHA256
       over the identity headers. Returns an ``AuthContext`` with an empty
       ``roles`` list (HMAC headers carry no role information).

    Requests without any gateway proof, with an invalid proof, with a stale
    timestamp, or with a mismatched signature are rejected with 401.

    Args:
        x_user_id: User UUID (HMAC path).
        x_tenant_id: Tenant UUID (HMAC path).
        x_user_email: User email (HMAC path).
        x_gateway_timestamp: Gateway signature timestamp (HMAC path).
        x_gateway_signature: Gateway HMAC-SHA256 proof (HMAC path).
        x_gateway_context: Short-lived RS256 JWT (RS256 path, takes priority).

    Returns:
        AuthContext with resolved user and tenant identity.

    Raises:
        HTTPException 401: Missing or invalid proof.
        HTTPException 503: Required service configuration is absent.
    """
    # RS256 JWT path — takes priority over HMAC when present.
    if x_gateway_context is not None:
        return _verify_rs256_gateway_context(x_gateway_context.strip())

    # HMAC path — check identity headers first (401 before 503).
    if not x_user_id or not x_tenant_id or not x_user_email:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Missing gateway identity headers (X-User-ID, X-Tenant-ID, X-User-Email).",
        )

    gateway_secret = os.getenv(GATEWAY_SHARED_SECRET_ENV)
    if not gateway_secret:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail={
                "status": "unavailable",
                "reason": "configuration_missing",
                "required_configuration": [GATEWAY_SHARED_SECRET_ENV],
            },
        )

    if not x_gateway_timestamp or not x_gateway_signature:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail=(
                "Missing gateway signature headers "
                "(X-Adaptix-Gateway-Timestamp, X-Adaptix-Gateway-Signature)."
            ),
        )

    try:
        gateway_timestamp = int(x_gateway_timestamp.strip())
    except (ValueError, AttributeError) as exc:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="X-Adaptix-Gateway-Timestamp header is not a valid Unix timestamp.",
        ) from exc

    if abs(int(time.time()) - gateway_timestamp) > GATEWAY_SIGNATURE_MAX_AGE_SECONDS:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Gateway identity signature has expired.",
        )

    try:
        user_uuid = UUID(x_user_id.strip())
    except (ValueError, AttributeError) as exc:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="X-User-ID header is not a valid UUID.",
        ) from exc

    try:
        tenant_uuid = UUID(x_tenant_id.strip())
    except (ValueError, AttributeError) as exc:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="X-Tenant-ID header is not a valid UUID.",
        ) from exc

    email = x_user_email.strip()
    signature_payload = f"{gateway_timestamp}.{user_uuid}.{tenant_uuid}.{email}".encode(
        "utf-8"
    )
    expected_signature = hmac.new(
        gateway_secret.encode("utf-8"),
        signature_payload,
        hashlib.sha256,
    ).hexdigest()
    if not hmac.compare_digest(expected_signature, x_gateway_signature.strip()):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Gateway identity signature is invalid.",
        )

    return AuthContext(
        user_id=user_uuid,
        tenant_id=tenant_uuid,
        email=email,
        roles=[],
    )


def build_gateway_context_jwt(
    *,
    user_id: UUID,
    tenant_id: UUID,
    email: str,
    roles: list[str],
    private_key_pem: str,
    issuer: str = "adaptix-core",
    audience: str | None = None,
    ttl_seconds: int = 60,
) -> str:
    """Sign a short-lived RS256 gateway context JWT for Core-to-service calls.

    Use this in Core or the gateway service when making direct internal calls
    to domain services. The resulting JWT should be sent as the
    ``X-Adaptix-Gateway-Context`` header.

    Args:
        user_id: Authenticated user UUID.
        tenant_id: Authenticated tenant UUID.
        email: Authenticated user email.
        roles: List of role strings from the validated user session.
        private_key_pem: RS256 private key PEM string.
        issuer: JWT issuer — "adaptix-gateway" or "adaptix-core".
        audience: Optional target service audience string.
        ttl_seconds: Token lifetime in seconds (default 60).

    Returns:
        Signed JWT string ready for the X-Adaptix-Gateway-Context header.

    Raises:
        RuntimeError: If PyJWT is not installed.
        ValueError: If the private key is empty.
    """
    if not private_key_pem or not private_key_pem.strip():
        raise ValueError("private_key_pem must not be empty.")

    try:
        import jwt as pyjwt
    except ImportError as exc:
        raise RuntimeError(
            "PyJWT is required for build_gateway_context_jwt. "
            "Install adaptix-contracts[jwt] or add PyJWT>=2.8.0."
        ) from exc

    now = int(time.time())
    from uuid import uuid4

    payload: dict = {
        "iss": issuer,
        "sub": str(user_id),
        "tid": str(tenant_id),
        "email": email,
        "roles": roles,
        "iat": now,
        "exp": now + ttl_seconds,
        "jti": str(uuid4()),
        "caller": issuer,
    }
    if audience:
        payload["aud"] = audience

    return pyjwt.encode(payload, private_key_pem, algorithm="RS256")


__all__ = [
    "AuthContext",
    "GATEWAY_SHARED_SECRET_ENV",
    "GATEWAY_PUBLIC_KEY_ENV",
    "GATEWAY_JWT_CONTEXT_HEADER",
    "GATEWAY_SIGNATURE_MAX_AGE_SECONDS",
    "build_gateway_context_jwt",
    "get_auth_context",
]
